package org.gem.ui.text

internal object ExpectedGemLocalizationLocales {
    val localeTags: List<String> = listOf(
        "cs-CZ",
        "da-DK",
        "de-DE",
        "el-GR",
        "en-GB",
        "es-ES",
        "et-EE",
        "fi-FI",
        "fr-FR",
        "hu-HU",
        "it-IT",
        "lt-LT",
        "lv-LV",
        "nb-NO",
        "nl-NL",
        "nn-NO",
        "pl-PL",
        "pt-BR",
        "pt-PT",
        "ro-RO",
        "sv-SE",
        "tr-TR",
        "uk-UA",
    )

    val nativeNamesByLocaleTag: Map<String, String> = mapOf(
        "cs-CZ" to "Čeština",
        "da-DK" to "Dansk",
        "de-DE" to "Deutsch",
        "el-GR" to "Ελληνικά",
        "en-GB" to "English",
        "es-ES" to "Español",
        "et-EE" to "Eesti",
        "fi-FI" to "Suomi",
        "fr-FR" to "Français",
        "hu-HU" to "Magyar",
        "it-IT" to "Italiano",
        "lt-LT" to "Lietuvių",
        "lv-LV" to "Latviešu",
        "nb-NO" to "Norsk bokmål",
        "nl-NL" to "Nederlands",
        "nn-NO" to "Norsk nynorsk",
        "pl-PL" to "Polski",
        "pt-BR" to "Português (Brasil)",
        "pt-PT" to "Português",
        "ro-RO" to "Română",
        "sv-SE" to "Svenska",
        "tr-TR" to "Türkçe",
        "uk-UA" to "Українська",
    )
}
