package org.gem.ui.design

import androidx.compose.runtime.Immutable
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

@Immutable
data class GemSpacing(
    val none: Dp = 0.dp,
    val borderWidth: Dp = 1.dp,
    val tapTarget: Dp = 48.dp,
    val pagePadding: Dp = 14.dp,
    val shellMaxWidth: Dp = 412.dp,
    val shellMaxHeight: Dp = 932.dp,
    val shellMinHeight: Dp = 760.dp,
    val desktopWindowWidth: Dp = 440.dp,
    val desktopWindowHeight: Dp = 780.dp,
    val topBarMinHeight: Dp = 72.dp,
    val brandLogoSize: Dp = 40.dp,
    val secondLifeTimeMinWidth: Dp = 72.dp,
    val secondLifeTimeMenuGap: Dp = 8.dp,
    val sessionStripMinHeight: Dp = 62.dp,
    val panelPadding: Dp = 16.dp,
    val fieldGap: Dp = 8.dp,
    val rowGap: Dp = 10.dp,
    val controlHeight: Dp = 56.dp,
    val appearanceExpandableHeaderHeight: Dp = 56.dp,
    val appearanceCompactFieldHeight: Dp = 28.dp,
    val appearanceSwatchMinHeight: Dp = 28.dp,
    val appearanceSwatchGap: Dp = 3.dp,
    val appearanceColorPickerGap: Dp = 12.dp,
    val appearanceRgbToneGap: Dp = 12.dp,
    val appearanceRgbRowGap: Dp = 8.dp,
    val appearanceRgbLabelWidth: Dp = 16.dp,
    val appearanceRgbFieldWidth: Dp = 44.dp,
    val appearanceTonePreviewWidth: Dp = 104.dp,
    val appearanceTonePreviewHeight: Dp = 64.dp,
    val appearanceSelectorRowGap: Dp = 8.dp,
    val appearanceProfileActionGap: Dp = 8.dp,
    val appearanceModalGap: Dp = 12.dp,
    val appearanceModalPadding: Dp = 14.dp,
    val compactRowMinHeight: Dp = 32.dp,
    val passwordRevealButtonWidth: Dp = 72.dp,
    val backIconSize: Dp = 18.dp,
    val themeToggleWidth: Dp = 36.dp,
    val themeToggleHeight: Dp = 20.dp,
    val themeToggleKnobSize: Dp = 14.dp,
    val themeToggleKnobInset: Dp = 3.dp,
    val themeToggleKnobCheckedOffset: Dp = 16.dp,
    val menuItemMinHeight: Dp = 30.dp,
    val menuItemHorizontalPadding: Dp = 12.dp,
    val menuItemVerticalPadding: Dp = 3.dp,
    val fieldHorizontalPadding: Dp = 12.dp,
    val rowVerticalPadding: Dp = 9.dp,
    val rowHorizontalPadding: Dp = 12.dp,
    val compactRowVerticalPadding: Dp = 4.dp,
    val rowIconSize: Dp = 42.dp,
    val inlineIconSize: Dp = 18.dp,
    val scrollbarWidth: Dp = 10.dp,
    val scrollbarMinThumbHeight: Dp = 24.dp,
    val scrollbarThickness: Dp = 8.dp,
    val scrollbarRadius: Dp = 4.dp,
    val statusPillMinHeight: Dp = 28.dp,
    val statusPillHorizontalPadding: Dp = 10.dp,
    val operationSpinnerSize: Dp = 14.dp,
    val noticeBodyMinHeight: Dp = 112.dp,
    val noticeBodyMaxHeight: Dp = 180.dp,
    val inventoryPaneMinHeight: Dp = 132.dp,
    val inventoryPaneMaxHeight: Dp = 220.dp,
    val groupPickerMaxHeight: Dp = 220.dp,
    val scrollListMaxHeight: Dp = 220.dp,
    val modalInset: Dp = 22.dp,
    val modalMaxWidth: Dp = 360.dp,
    val modalActionMinWidth: Dp = 112.dp,
    val inlineGap: Dp = 12.dp,
)
